<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MotionControl.Domain/MotionControl.Domain.csproj" />
    <ProjectReference Include="../../src/MotionControl.Application/MotionControl.Application.csproj" />
    <ProjectReference Include="../../src/MotionControl.Simulation/MotionControl.Simulation.csproj" />
    <ProjectReference Include="../../src/MotionControl.Persistence/MotionControl.Persistence.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
